### ISSUE TITLE
[Plugin name]: Title

### ISSUE THREAD

**Issue by xiaoman1221** [zhang-anzhi/MCDReforgedPlugins#11]
OnlinePlayerAPI.py

加载失败

报错：
[MCDR] [08:08:47] [MainThread/ERROR]: 插件 OnlinePlayerAPI.py 加载失败
Traceback (most recent call last):
  File "D:\我的世界服务器研究\MCFab1164\utils\plugin_manager.py", line 63, in load_plugin
    plugin.load()
  File "D:\我的世界服务器研究\MCFab1164\utils\plugin.py", line 82, in load
    self.module = tool.load_source(self.file_path)
  File "D:\我的世界服务器研究\MCFab1164\utils\tool.py", line 25, in load_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "plugins\OnlinePlayerAPI.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by zhang-anzhi** [comment]
请检查插件下载是否正确

**Comment by xiaoman1221** [comment]
是的，我已经解决了
