### ISSUE TITLE
QQChat 插件报错：ProxySchemeUnknown: Not supported proxy scheme None

### ISSUE THREAD

**Issue by RisingInIris2017** [zhang-anzhi/MCDReforgedPlugins#5]
### MCDR 版本
0.9.6
### 所有安装的插件
```
[MCDR] [15:16:13] [InfoReactor/INFO]: 8x 已加载插件
[MCDR] [15:16:13] [InfoReactor/INFO]: - CoolQAPI-MCDR.py
[MCDR] [15:16:13] [InfoReactor/INFO]: - daycount.py
[MCDR] [15:16:13] [InfoReactor/INFO]: - Here.py
[MCDR] [15:16:13] [InfoReactor/INFO]: - joinMOTD.py
[MCDR] [15:16:13] [InfoReactor/INFO]: - OnlinePlayerAPI.py
[MCDR] [15:16:13] [InfoReactor/INFO]: - QQChat.py
[MCDR] [15:16:13] [InfoReactor/INFO]: - QuickBackupM.py
[MCDR] [15:16:13] [InfoReactor/INFO]: - tps.py
[MCDR] [15:16:13] [InfoReactor/INFO]: 0x 已禁用插件
[MCDR] [15:16:13] [InfoReactor/INFO]: 0x 未加载插件
```
### 系统环境
Windows 10 专业工作站版，版本号 20H2
考虑到报错中包含 Proxy，我将“网络和 Internet 设置”中的“手动设置代理”设为“关”，但仍然没有解决问题。
环境变量中有一个`http_proxy`，值是`127.0.0.1:7890`，应该是代理软件 [ClashForWindows](https://github.com/Fndroid/clash_for_windows_pkg) 添加的，不确定有没有影响。
### 报错内容
```
[MCDR] [15:10:53] [PT0-on_info@QQChat/ERROR]: Error calling on_info in plugin QQChat
Traceback (most recent call last):
  File "C:\MARYT\MARYT Classic\utils\plugin_thread.py", line 41, in run
    task_data.func(*task_data.args)
  File "plugins\QQChat.py", line 267, in on_info
    send_private_msg(info.raw_content, a)
  File "plugins\QQChat.py", line 296, in send_private_msg
    requests.post(f'http://{host}:{port}/send_private_msg', json=data)
  File "C:\Program Files\Python39\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python39\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\requests\adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "C:\Program Files\Python39\lib\site-packages\requests\adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "C:\Program Files\Python39\lib\site-packages\requests\adapters.py", line 193, in proxy_manager_for
    manager = self.proxy_manager[proxy] = proxy_from_url(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\poolmanager.py", line 492, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "C:\Program Files\Python39\lib\site-packages\urllib3\poolmanager.py", line 429, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None
```
### 问题补充
这个问题是我在将 MCDR 连同服务端一起迁移到另一台机器上时出现的。
Minecraft 服务端可以正常工作，但是 QQChat 频繁产生上述报错，影响到了服务端控制台的正常使用。
我不能确定是因为什么原因产生的，希望能得到你的帮助。
非常感谢你的耐心帮助！

**Comment by zhang-anzhi** [comment]
该问题是系统网络问题导致的，不属于插件的问题
